version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_BASE_URL=${VITE_BASE_URL}
      - VITE_TOKEN_KEY=${VITE_TOKEN_KEY}
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped